version: "3"
services:

  postgres:
    container_name: strumming-db
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: strumming-db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /data/postgres
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  swagger-ui:
    container_name: "swagger-ui"
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes: ["./swagger.json:/swagger.json"]
    environment:
      - SWAGGER_JSON=/swagger.json
    restart: always

